apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment2
spec:
  selector:
    matchLabels:
      app: nginx2
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        command:
        - /bin/bash
        - -c
        - "echo '<html><body>2nd nginx</body></html>' >/usr/share/nginx/html/index.html && exec nginx -g 'daemon off;'"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx2
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx2
  type: LoadBalancer
