---
apiVersion: v1
kind: Service
metadata:
  name: virtletlb-outer
  labels:
    control-plane: virtletlb-outer
spec:
  selector:
    control-plane: virtletlb-outer
  ports:
  - port: 443
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: virtletlb-outer
spec:
  selector:
    matchLabels:
      control-plane: virtletlb-outer
  serviceName: virtletlb-outer
  template:
    metadata:
      name: virtletlb-outer
      labels:
        control-plane: virtletlb-outer
    spec:
      # serviceAccountName: virtlet
      containers:
      - name: virtletlb
        args: ["-v=2", "-logtostderr", "outer", "outer"]
        image: docker.io/ishvedunov/virtletlb
        env:
        - name: KUBECONFIG
          value: /etc/virtletlb/clusters.conf
        volumeMounts:
        - mountPath: /etc/virtletlb
          name: cluster-configs
      volumes:
      # FIXME: use service acoount!!!
      - name: cluster-configs
        secret:
          secretName: cluster-configs
# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: virtletlb
#   namespace: kube-system
# ---
# apiVersion: rbac.authorization.k8s.io/v1beta1
# kind: ClusterRoleBinding
# metadata:
#   name: virtletlb
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: virtletlb
# subjects:
# - kind: ServiceAccount
#   name: virtletlb
#   namespace: kube-system
# ---
# kind: ClusterRole
# apiVersion: rbac.authorization.k8s.io/v1beta1
# metadata:
#   name: virtletlb
#   namespace: kube-system
# rules:
# - apiGroups:
#   - ""
#   resources:
#   - services
#   verbs: ["*"]
# - apiGroups:
#   - "virtletlb.virtlet.cloud"
#   resources:
#   - innerservices
#   verbs: ["*"]
